---FIND OUT THE DEPARTMENT NAME AND THE MANAGER FIRST NAME
---FOR EACH DEPARTMENT

---FACT :MANAGER ID COLUMN OF DEPARTMENT TABLE
--- IS THE EMPLOYEE_ID OF THAT MANAGER
---ACCORDING TO THE DEPARTMENT TABLE MANAGER COLUMN COMMENT
---MANAGER ID IS FOREIGN KEY TO EMPLOYEE ID OF EMPLOYEE COLUMN
---IN S NUTSHELL, THAT IS THE RELATIONSHIP WE ARE GOING TO USE
---EMPLOYEE.EMPLOYEE id = DEPARTMENTS.MANAGER ID
---NOTE THAT COLUMN NAMES DOES NOT HAVE TO MATCH AS LONG AS RELATIONSHIP IS DEFINED
SELECT DEPARTMENTS.DEPARTMENT_NAME,EMPLOYEES.FIRST_NAME
FROM DEPARTMENTS
INNER JOIN EMPLOYEES ON DEPARTMENTS.MANAGER_ID = EMPLOYEES.EMPLOYEE_ID;

--THIS IS ALIAS VERSION
SELECT d.DEPARTMENT_NAME,e.FIRST_NAME
FROM DEPARTMENTS d
         INNER JOIN EMPLOYEES e ON d.MANAGER_ID =e.EMPLOYEE_ID;


---continue from above query , find out the manager first name of executive
SELECT d.DEPARTMENT_NAME,e.FIRST_NAME
FROM DEPARTMENTS d
INNER JOIN EMPLOYEES e ON d.MANAGER_ID =e.EMPLOYEE_ID
WHERE d.DEPARTMENT_NAME = 'Executive';

---continue from above query , filter the result if the department name
-- and the manager first name for each departments
--only display if department name start with a
---where .d .department nme like 'A%';

---FIND OUT HOW MANY COUNTRY IN EACH REGION
---DISPLAY NAME AND COUNTRY COUNT

SELECT REGION_NAME, COUNT (COUNTRIES.COUNTRY_NAME) AS "COUNTRY_COUNT"
FROM COUNTRIES
INNER JOIN REGIONS ON COUNTRIES.REGION_ID = REGIONS.REGION_ID
GROUP BY REGION_NAME;




