---SUB QUERY : QUERY INSIDE ANOTHER QUERY

--FIND OUT MAX SALARY FROM EMPLOYEES

SELECT MAX(SALARY)
FROM EMPLOYEES;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = 24000;

--- WE HARD CODED THE VALUE OF 24000 WE GOT FROM FIRST QUERY INTO SECOND QUERY
---NOW JUST LIKE FUNCTION CALL WE CAN USE THIS QUERY
--AS A BLOCK OF QUERY THAT GENERATE MAX SALARY ANYTIME
--SO EVEN IF MAX SALARY CHANGE AT SOE POINT WE WOULD GET CORRECT RESULT

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY= (SELECT MAX(SALARY) FROM EMPLOYEES) ;

SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

---FIND OUT EVERYONE THE NAME OF EMPLOYEES THAT MAKE MORE THAN AVERAGE SALARY

SELECT AVG(SALARY)  FROM EMPLOYEES;

SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES);

---DISPLAY ALL EMPLOYEES IF SALARY IS NOT 24000;
--AND FIND MAX
--AKA SECOND MAX SALARY
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY !=(SELECT MAX(SALARY) FROM EMPLOYEES);

--FIND OUT 3RD MAX SALARY
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY< 17000 ; ---FILTER ALL SALARY LESS THAN 2ND ONE
---JUST REPLACE THE 17000 WITH ABOVE QUERY

SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY<  (SELECT MAX(SALARY)
                FROM EMPLOYEES
                WHERE SALARY !=(SELECT MAX(SALARY) FROM EMPLOYEES));


---FIND OUT THE FIRST NAME OF EMPLOYEES WHO WORKS IN THE EXCUTIVE DEPARTMENT

---find out the department id of excutive

SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'Executive';

SELECT FIRST_NAME FROM EMPLOYEES
    WHERE DEPARTMENT_ID =90;


SELECT FIRST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS
                       WHERE DEPARTMENT_NAME = 'Executive'  ) ;

--FIND OUT THE FIRST NAME OF EMPLOYEES
--WHO WORKS IN EXECUTIVE AND ADMINISTRATIVE DEPARTMENT

SELECT FIRST_NAME
FROM EMPLOYEES;


--FIND OUT THE DEPARTMENT ID OF EXECUTIVE
--AND ADMINISTRATIVE DEPARTMENT

SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_NAME IN ('Executive', 'Administrative');

--FIND OUT THE FIRST NAME OF EMPLOYEES WHO WORKS IN DEPARMENT _ID 90 AND 10
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(90,10);

---combine the result

SELECT FIRST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(SELECT DEPARTMENT_ID FROM DEPARTMENTS
                       WHERE DEPARTMENT_NAME IN ('Executive', 'Administrative'));

---RESULT OF SUB QUERY CAN ALSO BE USED AS ENTIRE TABLE
--FOR EXAMPLE SELECT * FROM (SUB QUERY GOES HERE)

SELECT FIRST_NAME,LAST_NAME,(FIRST_NAME ||EMPLOYEES.LAST_NAME) AS FULL_NAME
FROM EMPLOYEES
---WHERE FULL_NAME = 'EllenAbel' ; we can not use alias in condition
;

SELECT *
FROM (SELECT FIRST_NAME,(FIRST_NAME ||EMPLOYEES.LAST_NAME) AS FULL_NAME
       FROM EMPLOYEES)
WHERE FULL_NAME ='EllenAbel';

--FIND OUT THE EMPLOYEE COUNT OF THE DEPARTMENT  WITH MAX EMPLOYEE COUNT
SELECT DEPARTMENT_ID,COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT MAX(EMPLOYEE_COUNT)
FROM (SELECT DEPARTMENT_ID,COUNT(*) AS EMPLOYEE_COUNT
      FROM EMPLOYEES
      GROUP BY DEPARTMENT_ID);


---FIND OUT DEPARTMENT_ID OF THAT THE DEPARTMENT WITH MOST EMPLOYEE


---DENSE_RANK FUNCTION THAT FALL INTO CATEGORY OF ANALYTICAL FUNCTIONS
--DENSE_RANK() OVER(ORDER BY SALARY)
SELECT FIRST_NAME,SALARY,
       DENSE_RANK() OVER(ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;

--NOW WE CAN SEE THIS WHOLE RESULT OF ABOVE QUERY AS A TABLE
--SELECT FROM THIS "TABLE" AND FILTER THE RESULT
--BY SALARY_RANK = NTH(THE NUMBER YOU WANT)
SELECT *
FROM (SELECT FIRST_NAME,SALARY,
             DENSE_RANK() OVER(ORDER BY SALARY DESC) AS SALARY_RANK
      FROM EMPLOYEES)
WHERE SALARY_RANK =3;

CREATE TABLE EMP_SALARY_RANK AS(
    SELECT FIRST_NAME,SALARY,
           DENSE_RANK() OVER(ORDER BY SALARY DESC) AS SALARY_RANK
    FROM EMPLOYEES
);





