SELECT EMPLOYEES.FIRST_NAME
FROM EMPLOYEES;

SELECT bla.FIRST_NAME
FROM EMPLOYEES bla;

------SQL JOIN-------------
--- IS USED TO GET DATA FROM 2 OR MORE TABLES THAT RELATED TO EACH OTHER
-- PRIMARY KEY AND FOREIGN KEY RELATIONSHIP

----INNER JOIN, LEFT OUTER JOIN, RIGHT OUTER JOIN, FULL OUTER JOIN
--IN ORDER TO JOIN TWO TABLES THAT HAS RELATIONSHIP
--SELECT DESIRED COLUMNS FROM BOTH TABLES
-- FROM TABLE 1
--INNER JOIN TABLE 2 ON THE COMMON COLUMN

SELECT COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME
FROM COUNTRIES
INNER JOIN REGIONS ON REGIONS.REGION_ID = COUNTRIES.REGION_ID;

--we can use alias for table to make above query slightly more readable
--nicknames are followed by space and the letter or word
-- you can use nickname to select the columns
--just like you did in java obj.VariableName

SELECT c.COUNTRY_NAME, r.REGION_NAME
FROM COUNTRIES c
INNER JOIN REGIONS r ON c.REGION_ID = r.REGION_ID;

---Find out location


